# Generated by Django 4.0.6 on 2024-04-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praia',
            name='localizacao',
        ),
    ]
