# Generated by Django 4.0.6 on 2024-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_banda_ativa_banda_cidade_origem_banda_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='copies_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='banda',
            name='premios_ganhos',
            field=models.IntegerField(default=0),
        ),
    ]
